### ISSUE TITLE
Clipping 

### ISSUE THREAD

**Issue by MickCoelho** [imaaronjames/Simple-Android-Ripple#1]
Hey,

Seems like with the recent updates, you now need to force the btn to clip his children
`btn.clip = true`

**Comment by imaaronjames** [comment]
@MickCoelho Feel free to submit a pull request to update this. Thanks.

**Comment by imaaronjames** [comment]
This issue is now fixed in https://github.com/imaaronjames/Simple-Android-Ripple/commit/c3b5967a7e6805b6034f946f0a651f855a510898
