### ISSUE TITLE
Call event from other layer

### ISSUE THREAD

**Issue by aaronmoodie** [imaaronjames/Simple-Android-Ripple#4]
How would you call Ripple from another layer? as an event handler, should you be able to call `Android.Ripple(event, layerName)` ? 

I'm trying to do something like this: 

```
layer1.onClick (event, layer) ->
    Android.Ripple(event, layer2)
```

**Comment by imaaronjames** [comment]
Sorry @aaronmoodie ,
It's not setup to work that way. I'm also a Framer noob. haha. You will need to extrapolate the code from the module to make it work for your needs. Feel free to submit a pull request if you find a better way.

**Comment by aaronmoodie** [comment]
thanks @imaaronjames - sure thing! I ended up working out a way to do what I wanted, but will take a look at a PR to add that in. Would be helpful in future. Thanks!
