### ISSUE TITLE
Not working on latest version of Framer

### ISSUE THREAD

**Issue by rssems** [imaaronjames/Simple-Android-Ripple#5]
![screen shot 2016-05-23 at 4 22 58 pm](https://cloud.githubusercontent.com/assets/847648/15487511/a5a0aacc-2102-11e6-91ea-41dc7323a4f2.png)

Framer v63

Error msg: [framer.js] Error: Layer.on needs an event listener

**Comment by imaaronjames** [comment]
Everything appears to be working when I test on my end (v63). Double check with this below. 

```
Android = require "androidRipple"

bg = new BackgroundLayer
    backgroundColor: "#eeeeee"

btn = new Layer
    width: 800, height: 200
    backgroundColor: "#fafafa"
    borderRadius: 12
    shadowX: 0
    shadowY: 6
    shadowBlur: 6
    shadowColor: "rgba(0,0,0,0.24)"
    clip: true ## buttons must include clip
btn.center()
btn.on(Events.Click, Android.Ripple)
```

**Comment by rssems** [comment]
It's working perfectly, sorry my bad :) Thank you!
