### ISSUE TITLE
Ripple effect boundaries 

### ISSUE THREAD

**Issue by rssems** [imaaronjames/Simple-Android-Ripple#6]
Hi again Aaron,

Thank you again for this great module!

Your original demo: http://share.framerjs.com/aqzkcamx0iqw/
Same module on newest version of Framer: http://share.framerjs.com/0xcsmy4c9i0j/

As you can see ripple effect boundaries are no longer working, I think it's related to masking.

Can we fix this?

Best.

**Comment by rssems** [comment]
I think this related to working with masks (clipping layers) and **rounded corners**.

**Comment by rssems** [comment]
Temporary solution:

I created a parent layer and clipped it.

```
materialBtnOverlay = new Layer
    clip: true
materialBtn = new Layer
    parent: materialBtnOverlay
materialBtn.on(Events.Click, android.ripple)
```

**Comment by imaaronjames** [comment]
Hi @rssems 
Framer use to mask layers by default. Looks like they changed that behavior in v63. I've updated the code on in the readme file to reflect this change. All layers that use this module must include "clip: true"

**Comment by rssems** [comment]
Thank you @imaaronjames for updating the module quickly! Best.
